---
title: "Apex_TPC_Ramp"
author: "HM Putnam"
date: "2024-03-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
```


```{r}
bath <- read.csv("data/TPC/Ramp_Test/21723477_Bath_2024-03-02_17_35_03.csv")
colnames(bath) <- c("num", "Date.Time", "Temp.C")
bath$name <- "bath"
bath <- bath %>%
  filter(Date.Time > "03/02/2024 13:32:00") %>%
  filter(Date.Time < "03/02/2024 17:32:00")


chamb1 <- read.csv("data/TPC/Ramp_Test/21723472_Chamber1_2024-03-02_17_35_38.csv")
colnames(chamb1) <- c("num", "Date.Time", "Temp.C")
chamb1$name <- "chamber1"
chamb1 <- chamb1 %>%
  filter(Date.Time > "03/02/2024 13:32:00") %>%
  filter(Date.Time < "03/02/2024 17:32:00")

chamb15 <- read.csv("data/TPC/Ramp_Test/21723473_Chamber15_2024-03-02_17_36_12.csv")
colnames(chamb15) <- c("num", "Date.Time", "Temp.C")
chamb15$name <- "chamber15"
chamb15 <- chamb15 %>%
  filter(Date.Time > "03/02/2024 13:32:00") %>%
  filter(Date.Time < "03/02/2024 17:32:00")

```

Plot data
```{r}
data <- rbind(bath, chamb1, chamb15)
str(data)
data$Date.Time<-as.POSIXct(data$Date.Time, format="%m/%d/%Y %H:%M:%S", tz="Pacific/Tahiti")
str(data)

data %>%
  ggplot(aes(x = Date.Time, y = Temp.C,color=name)) +
  geom_point(size = 1) +
  #scale_x_continuous(breaks = seq(10))+
  theme_classic()

```

PIC
```{r}
data <- read.csv("data/TPC/Run5_21723472 2024-03-14_13_19_56.csv")
colnames(data) <- c("num", "Date.Time", "Temp.C")

PIC <- data %>%
  filter(Date.Time > "03/04/2024 16:45:00") %>%
  filter(Date.Time < "03/04/2024 19:00:00")

PIC$name <- "PIC"

PIC %>%
  ggplot(aes(x = Date.Time, y = Temp.C, color=name)) +
  geom_point(size = 1) +
  #scale_x_continuous(breaks = seq(10))+
  theme_classic()
```

Run2
```{r}
Run2 <- data %>%
  filter(Date.Time > "03/05/2024 13:15:00") %>%
  filter(Date.Time < "03/05/2024 19:56:00")
Run2$name <- "Run2"

Run2 %>%
  ggplot(aes(x = Date.Time, y = Temp.C, color=name)) +
  geom_point(size = 1) +
  #scale_x_continuous(breaks = seq(10))+
  theme_classic()
```


Run3
```{r}
Run3 <- data %>%
  filter(Date.Time > "03/09/2024 12:45:00") %>%
  filter(Date.Time < "03/09/2024 20:29:00")
Run3$name <- "Run3"

Run3 %>%
  ggplot(aes(x = Date.Time, y = Temp.C, color=name)) +
  geom_point(size = 1) +
  #scale_x_continuous(breaks = seq(10))+
  theme_classic()
```

Run4
```{r}
Run4 <- data %>%
  filter(Date.Time > "03/10/2024 13:15:00") %>%
  filter(Date.Time < "03/10/2024 20:33:00")
Run4$name <- "Run4"

Run4 %>%
  ggplot(aes(x = Date.Time, y = Temp.C, color=name)) +
  geom_point(size = 1) +
  #scale_x_continuous(breaks = seq(10))+
  theme_classic()
```

Run5
```{r}
Run5 <- data %>%
  filter(Date.Time > "03/13/2024 11:52:00") %>%
  filter(Date.Time < "03/13/2024 19:00:00")
Run5$name <- "Run5"

Run5 %>%
  ggplot(aes(x = Date.Time, y = Temp.C, color=name)) +
  geom_point(size = 1) +
  #scale_x_continuous(breaks = seq(10))+
  theme_classic()
```